In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

In [12]:
df = pd.read_csv('/home/christel/code/domangechristel-ship-it/Project/garmin_guard/data/processed/training_load_features.csv')

In [13]:
df.head()

,athlete_date,daily_tss,n_sessions,total_distance_m,total_duration_s,avg_hr,body_battery_delta,atl_7d,ctl_42d,tsb,acwr,has_session,consecutive_training_days,load_spike_pct,acwr_zone
0,2023-04-02,8.178606,1.0,5900.3,2118.2,139.0,0.0,8.18,8.18,0.00,1.000,1,1,NaN,optimal
1,2023-04-03,0.000000,0.0,0.0,0.0,NaN,NaN,6.13,7.80,1.67,0.786,0,0,NaN,sous-charge
2,2023-04-04,0.000000,0.0,0.0,0.0,NaN,NaN,4.60,7.44,2.84,0.618,0,0,NaN,sous-charge
3,2023-04-05,15.938903,2.0,11146.5,3831.8,149.5,0.0,7.44,7.83,0.39,0.950,1,1,NaN,optimal
4,2023-04-06,0.000000,0.0,0.0,0.0,NaN,NaN,5.58,7.47,1.89,0.747,0,0,NaN,sous-charge

In [14]:
data = pd.read_csv('/home/christel/code/domangechristel-ship-it/Project/garmin_guard/data/processed/activities_normalized.csv')
data.head()

,activity_id,name,sport_type,location,start_utc,start_local,athlete_date,distance_m,duration_s,moving_s,...,hr_zone_6_s,lap_count,device_id,moderate_intensity_min,vigorous_intensity_min,is_pr,elev_corrected,start_lat,start_lon,source
0,10820369885,Villeurbanne Course à pied,RUNNING,Villeurbanne,2023-04-02 13:24:17,2023-04-02 15:24:17,2023-04-02,5900.3,2118.2,2116.8,...,0.0,6.0,3.970549e+09,NaN,NaN,False,True,45.774603,4.865225,garmin
1,10839296659,Villeurbanne Course à pied,RUNNING,Villeurbanne,2023-04-05 08:35:15,2023-04-05 10:35:15,2023-04-05,5123.9,1843.1,1826.2,...,0.0,6.0,3.970549e+09,21.0,7.0,False,True,45.775452,4.866299,garmin
2,10839297875,Lyon Course à pied,RUNNING,Lyon,2023-04-05 09:19:21,2023-04-05 11:19:21,2023-04-05,6022.6,1988.7,1986.5,...,0.0,7.0,3.970549e+09,7.0,26.0,False,True,45.763643,4.838822,garmin
3,10877047127,Villeurbanne Course à pied,RUNNING,Villeurbanne,2023-04-10 18:31:33,2023-04-10 20:31:33,2023-04-10,6206.2,2063.8,2058.1,...,0.0,7.0,3.436462e+09,1.0,33.0,False,False,45.774975,4.865039,garmin
4,10887998992,Villeurbanne Course à pied,RUNNING,Villeurbanne,2023-04-12 08:47:44,2023-04-12 10:47:44,2023-04-12,15164.0,5443.0,5433.4,...,0.0,16.0,3.436462e+09,1.0,90.0,False,False,45.775216,4.865223,garmin